global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: []

  - job_name: 'services'
    metrics_path: /metrics
    static_configs:
      - targets: ['admin-api:8080','jobs-svc:9101','route-svc:9102','billing-svc:9103','auth-svc:9104','observe-svc:9105','cdr-svc:9106']